'use client';

import React, { useState } from 'react';
import { 
  BarChart2, 
  MapPin, 
  Sparkles, 
  Calendar, 
  AlertTriangle, 
  ShieldCheck, 
  TrendingUp, 
  Brain,
  Zap,
  Info
} from 'lucide-react';
import { ISSUE_CATEGORIES } from '@civicmind/shared/dist/constants/categories';

// AI Predictions database
const MOCK_PREDICTIONS = [
  {
    id: 'pred-1',
    category: 'pothole',
    address: 'Dwarka Sector 12 Corridor, Delhi',
    probability: 84,
    timeframe: 'Next 30 Days (Monsoon arrival)',
    confidence: 0.91,
    reasoning: 'Corridor features aging asphalt layer coupled with high heavy-vehicle (bus/transit) count. Seasonal monsoon forecast estimates 120mm rainfall.',
    preventiveMeasures: [
      'Pre-apply micro-surfacing layer seal',
      'Conduct clearing of stormwater side drains',
      'Deploy speed restriction signage'
    ]
  },
  {
    id: 'pred-2',
    category: 'garbage',
    address: 'Sector 23 Market Square, Delhi',
    probability: 79,
    timeframe: 'Next 14 Days (Festival season)',
    confidence: 0.88,
    reasoning: 'Market foot traffic is estimated to increase by 45% due to upcoming community festivals. Historic dumping logs show waste bins exceed capacities by 2.4x.',
    preventiveMeasures: [
      'Increase garbage container count by 3 units',
      'Double collection frequency to twice daily',
      'Install educational display posters'
    ]
  },
  {
    id: 'pred-3',
    category: 'drainage',
    address: 'Block C main interceptor, Sector 8, Dwarka',
    probability: 71,
    timeframe: 'Next 30 Days (Pre-monsoon)',
    confidence: 0.85,
    reasoning: 'Line segment connects low-elevation sewers currently operating at 82% design loads. High debris sediment accumulation noted in seasonal inspection.',
    preventiveMeasures: [
      'Execute hydro-jetting pipeline desilting',
      'Verify auxiliary pump battery systems',
      'Clear solid waste items blockages'
    ]
  }
];

export default function AdminAnalyticsPage() {
  const [selectedPred, setSelectedPred] = useState<any>(MOCK_PREDICTIONS[0]);

  const getProbabilityStyles = (prob: number) => {
    if (prob >= 80) return 'text-red-700 border-red-200 bg-red-50';
    if (prob >= 60) return 'text-orange-700 border-orange-200 bg-orange-50';
    return 'text-amber-700 border-amber-200 bg-amber-50';
  };

  return (
    <div className="space-y-6 text-slate-800">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-5">
        <div className="text-left">
          <h1 className="text-2xl font-black tracking-tight text-[#0b2240]">AI Hotspot Predictions</h1>
          <p className="text-slate-550 text-xs mt-1 font-semibold">Geospatial risk analysis and preventative maintenance schedules generated by the Prediction Agent.</p>
        </div>

        <div className="flex items-center gap-1.5 px-3.5 py-2 bg-purple-50 border border-purple-200 rounded-xl text-xs font-bold text-purple-700 shrink-0 self-start sm:self-auto uppercase tracking-wide">
          <Brain className="h-4 w-4" />
          <span>Prediction Swarm: Active</span>
        </div>
      </div>

      {/* Main predictions grid split */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Predictions list items */}
        <div className="space-y-4">
          <h2 className="text-xs font-extrabold uppercase tracking-widest text-[#0b2240] flex items-center gap-1.5">
            <Zap className="h-4.5 w-4.5 text-[#2563eb]" />
            <span>High Probability Forecasts</span>
          </h2>

          <div className="space-y-3">
            {MOCK_PREDICTIONS.map((pred) => {
              const catConfig = ISSUE_CATEGORIES.find((c) => c.id === pred.category);
              const isSelected = selectedPred.id === pred.id;
              
              return (
                <button
                  key={pred.id}
                  onClick={() => setSelectedPred(pred)}
                  className={`w-full text-left p-4 rounded-2xl border transition-all flex flex-col justify-between gap-3 cursor-pointer ${
                    isSelected 
                      ? 'bg-blue-50 border-blue-200 shadow-sm' 
                      : 'bg-white border-slate-200 hover:border-slate-350'
                  }`}
                >
                  <div className="flex justify-between items-start w-full">
                    <div>
                      <span className="text-xs font-bold text-[#0b2240] flex items-center gap-1">
                        <span>{catConfig?.icon || '📋'}</span>
                        <span>{catConfig?.label || pred.category}</span>
                      </span>
                      <p className="text-[10px] text-slate-500 font-semibold mt-0.5">{pred.address}</p>
                    </div>
                    <div className={`text-[10px] font-mono font-bold px-2 py-0.5 border rounded ${getProbabilityStyles(pred.probability)}`}>
                      {pred.probability}% Prob
                    </div>
                  </div>
                  
                  <div className="text-[10px] text-slate-500 flex items-center gap-1 font-semibold">
                    <Calendar className="h-3.5 w-3.5" />
                    <span>Timeframe: {pred.timeframe}</span>
                  </div>
                </button>
              );
            })}
          </div>
        </div>

        {/* Middle/Right: Selected prediction details */}
        <div className="lg:col-span-2 space-y-6">
          {/* Detailed analysis panel */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm space-y-4 text-left">
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-4">
              <div>
                <span className="text-[10px] font-mono font-bold text-slate-500 bg-slate-50 px-2 py-0.5 border border-slate-200 rounded uppercase">
                  Forecast Index
                </span>
                <h3 className="text-base font-extrabold text-[#0b2240] mt-1.5 capitalize">
                  Predicted {selectedPred.category.replace('_', ' ')} incident
                </h3>
              </div>

              <div className="text-[11px] font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-3 py-1 rounded-full flex items-center gap-1">
                <Brain className="h-3.5 w-3.5" />
                <span>AI Confidence: {(selectedPred.confidence * 100).toFixed(0)}%</span>
              </div>
            </div>

            {/* Analysis details */}
            <div className="space-y-3.5 text-xs">
              <div>
                <span className="text-[9px] uppercase font-bold text-slate-450">Risk Location Target</span>
                <p className="font-semibold text-[#0b2240] mt-0.5 flex items-center gap-1.5">
                  <MapPin className="h-4 w-4 text-[#2563eb]" />
                  <span>{selectedPred.address}</span>
                </p>
              </div>

              <div>
                <span className="text-[9px] uppercase font-bold text-slate-450">Analytical Reasoning Statement</span>
                <p className="text-slate-600 leading-relaxed mt-0.5 font-semibold">{selectedPred.reasoning}</p>
              </div>

              {/* Recommended Preventive Actions */}
              <div className="space-y-2 pt-2 border-t border-slate-100">
                <span className="text-[9px] uppercase font-bold text-slate-450">AI Recommended Preventive Actions</span>
                <div className="space-y-2">
                  {selectedPred.preventiveMeasures.map((measure: string, idx: number) => (
                    <div key={idx} className="p-3 bg-[#f8fafc] border border-slate-200 rounded-xl flex items-center gap-3">
                      <div className="h-6 w-6 bg-emerald-50 text-emerald-700 rounded-lg flex items-center justify-center shrink-0 border border-emerald-200">
                        <ShieldCheck className="h-3.5 w-3.5" />
                      </div>
                      <span className="text-xs text-slate-600 font-semibold">{measure}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Mini info warning about predictive actions */}
          <div className="p-4 bg-blue-50 border border-blue-200 rounded-2xl flex items-start gap-3">
            <Info className="h-5 w-5 text-[#2563eb] shrink-0 mt-0.5" />
            <div>
              <h4 className="text-xs font-bold text-[#0b2240]">Preventative Dispatch Workflow</h4>
              <p className="text-[11px] text-slate-600 mt-0.5 font-semibold">Admins can click recommended actions to draft preventative work orders to corresponding department supervisors before active incidents manifest.</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
